// Generated by Selenium IDE

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class LoginTest extends  Hooks {
  public LoginPage loginPage;



  @Before
  public void setupPageObject() {
    loginPage = new LoginPage(driver);
    driver.manage().window().maximize();
  }

  @Test
  public void login() throws InterruptedException {

  loginPage.clickAccountButton();
  loginPage.getLoginButton();
  loginPage.getSignInForm();
  loginPage.getClickLogin();
  Thread.sleep(3000);
  assertEquals("MY DASHBOARD", loginPage.pageTitle.getText());
  loginPage.clickNewsletter();
  assertEquals("NEWSLETTER SUBSCRIPTION", loginPage.pageTitle.getText());
  loginPage.clickSubscribe();
  assertEquals("The subscription has been saved.", loginPage.subscriptionMessage.getText());
  loginPage.clickProfile();
  Thread.sleep(2500);
  loginPage.clickLogout();
  assertEquals("YOU ARE NOW LOGGED OUT", loginPage.logoutMessage.getText());
  }
}

